/**
 * Brand colors from theme.config.js as NativeWind tokens via NativeWind's
 * `platformColor()` (compiles to React Native's `PlatformColor(name)`), backed
 * by the named asset-catalog colorsets generated by plugins/withAccentColor.js,
 * so they adapt to Light/Dark Mode automatically (needs a native build made
 * after the colorsets exist — unknown colorset names render transparent).
 * Note: a hand-built `{ semantic: [...] }` object does NOT work here —
 * NativeWind needs its own helper to emit PlatformColor at runtime.
 */
const { platformColor } = require('nativewind/theme');

const brand = require('./theme.config.js');

const t = (name) => platformColor(brand[name].asset);
const fixed = brand.fixed;

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // --- Surfaces ---
        bg: t('bg'),
        surface: t('surface'),
        'surface-raised': t('surfaceRaised'),
        'surface-high': t('surfaceHigh'),
        line: t('separator'),
        'line-soft': t('border'),
        // --- Text ---
        label: t('label'),
        'label-secondary': t('labelSecondary'),
        'label-tertiary': t('labelTertiary'),
        // --- Brand ---
        tint: t('accent'),
        'on-tint': t('onAccent'),
        'tint-soft': t('accentSoft'),
        bonus: t('bonus'),
        'bonus-soft': t('bonusSoft'),
        destructive: t('danger'),
        'destructive-soft': t('dangerSoft'),
        warning: t('warning'),
        success: t('success'),
        foam: t('foam'),
        // --- Macros ---
        protein: t('protein'),
        'protein-soft': t('proteinSoft'),
        carbs: t('carbs'),
        'carbs-soft': t('carbsSoft'),
        fat: t('fat'),
        'fat-soft': t('fatSoft'),
        // --- Always-dark hero block (fixed hex, mode-independent) ---
        'hero-label': fixed.heroLabel,
        'hero-label-2': fixed.heroLabel2,
        'hero-track': fixed.heroTrack,
        // --- Legacy aliases (pre-identity names; keep so old screens work) ---
        'secondary-label': t('labelSecondary'),
        'tertiary-label': t('labelTertiary'),
        'system-background': t('bg'),
        'secondary-system-background': t('surface'),
        'system-grouped-background': t('bg'),
        'secondary-system-grouped-background': t('surface'),
        separator: t('separator'),
        'opaque-separator': t('separator'),
      },
      // Custom fonts: never combine with `font-bold` (iOS would fake-embolden).
      fontFamily: {
        display: ['BricolageGrotesque_600SemiBold'],
        'display-bold': ['BricolageGrotesque_700Bold'],
        'display-black': ['BricolageGrotesque_800ExtraBold'],
      },
      borderRadius: {
        inner: '16px',
        card: '24px',
        hero: '32px',
      },
    },
  },
  plugins: [],
};
