/**
 * møni brand tokens – single source of truth (identity v2 "Nachtschicht im Fjord").
 * Change a value HERE and everything follows: NativeWind tokens
 * (tailwind.config.js), the iOS asset-catalog colorsets (plugins/withAccentColor.js,
 * needs a prebuild/native rebuild), and src/theme/colors.ts.
 *
 * asset    = asset-catalog colorset name generated by plugins/withAccentColor.js.
 *            Used via PlatformColor(asset) → dynamic Light/Dark, also seen by
 *            native controls. An unknown name renders transparent, so tokens
 *            only work in a binary built after the colorsets were generated.
 * platform = iOS semantic fallback (informational / tests).
 * light/dark = hex (or rgba()) for Skia canvases and the colorset generator.
 *
 * Plain CommonJS so tailwind.config.js and the config plugin (Node) can require it.
 */
const c = (asset, platform, light, dark) => ({ asset, platform, light, dark });

module.exports = {
  // --- Brand ---
  accent: c('MoniAccent', 'systemGreen', '#1D6B47', '#C6F135'),
  onAccent: c('MoniOnAccent', 'systemBackground', '#F5F1E8', '#0C0F0D'),
  accentSoft: c(
    'MoniAccentSoft',
    'secondarySystemBackground',
    '#E4EBE3',
    '#313C1C',
  ),
  /** Workout bonus / energy ("ember" in the docs). */
  bonus: c('MoniBonus', 'systemOrange', '#C2410C', '#FF8A3D'),
  bonusSoft: c(
    'MoniBonusSoft',
    'secondarySystemBackground',
    '#F8E6DC',
    '#3A2C1D',
  ),
  danger: c('MoniDanger', 'systemRed', '#C62F3A', '#FF5C66'),
  dangerSoft: c(
    'MoniDangerSoft',
    'secondarySystemBackground',
    '#F8E4E1',
    '#3A2524',
  ),
  warning: c('MoniWarning', 'systemYellow', '#9A6700', '#FFB020'),
  success: c('MoniSuccess', 'systemGreen', '#2F7D3A', '#6EE08A'),

  // --- Macros (+ soft tints). Always pair with a letter/shape marker. ---
  protein: c('MoniProtein', 'systemPurple', '#6A4FE0', '#A18BFF'),
  proteinSoft: c(
    'MoniProteinSoft',
    'secondarySystemBackground',
    '#EDE8F5',
    '#2B2C3C',
  ),
  carbs: c('MoniCarbs', 'systemYellow', '#B87A00', '#FFCB3D'),
  carbsSoft: c(
    'MoniCarbsSoft',
    'secondarySystemBackground',
    '#F6EDDA',
    '#3A361D',
  ),
  fat: c('MoniFat', 'systemCyan', '#0B7FA8', '#4CCBF2'),
  fatSoft: c('MoniFatSoft', 'secondarySystemBackground', '#E2EEEE', '#1E363A'),

  // --- Surfaces S0..S3 ---
  bg: c('MoniBg', 'systemBackground', '#F5F1E8', '#0C0F0D'),
  surface: c('MoniSurface1', 'secondarySystemBackground', '#FFFDF8', '#151A17'),
  surfaceRaised: c(
    'MoniSurface2',
    'tertiarySystemBackground',
    '#ECE7DA',
    '#1D2420',
  ),
  surfaceHigh: c('MoniSurface3', 'quaternarySystemFill', '#E1DBCB', '#272F2A'),
  separator: c('MoniSeparator', 'separator', '#E2DDD0', '#2A302C'),
  /** Card inner hairline (alpha). */
  border: c(
    'MoniBorder',
    'separator',
    'rgba(27,26,22,0.06)',
    'rgba(245,242,234,0.08)',
  ),

  // --- Text ---
  label: c('MoniLabel', 'label', '#1B1A16', '#F5F2EA'),
  labelSecondary: c(
    'MoniLabelSecondary',
    'secondaryLabel',
    '#5B574D',
    '#A8A69B',
  ),
  labelTertiary: c('MoniLabelTertiary', 'tertiaryLabel', '#6F6A5E', '#82857B'),

  // --- Celebration light points (D2: "foam", formerly "spark") ---
  foam: c('MoniFoam', 'systemMint', '#1D6B47', '#E9FF9E'),

  /**
   * Fixed (mode-independent) colors for the always-dark hero block and Skia
   * canvases. Plain strings, no PlatformColor needed.
   */
  fixed: {
    lime: '#C6F135',
    limeHead: '#E9FF9E',
    limeStart: '#9BE564',
    limeMid: '#D4F55A',
    limeGlow: '#5EE6A0',
    foam: '#E9FF9E',
    forestTop: '#1D4F3B',
    forestBot: '#0F2A20',
    forest: '#183F31',
    ink: '#0C0F0D',
    paper: '#F5F1E8',
    heroLabel: '#F5F2EA',
    heroLabel2: '#A9C7B8',
    heroTrack: 'rgba(245,242,234,0.12)',
    ember: '#FF8A3D',
    emberHead: '#FFB066',
    emberHot: '#FF5C3A',
    protein: '#A18BFF',
    carbs: '#FFCB3D',
    fat: '#4CCBF2',
    danger: '#FF5C66',
  },
};
